### PR TITLE
Harris Hawks Optimization integration

### PR DESCRIPTION
**Pull request by sisco0**
### Summary

The Harris Hawks Optimization Algorithm has been integrated into _NiaPy_.

This algorithm goes on the line of _Nature inspired optimization algorithms_.

Having completeness and state-of-the-art as a goal for the _NiaPy_ project, this 
algorithm has been added, as it has been recently published (2019) in a JCR journal.

Unitary tests for the algorithm has been added as well.

### Other Information

As this is my first algorithm integration development, please take care at its review.
I would be happy to fix the issues found at it as well.

I used _BatAlgorithm_ as a template for writing this script.

Even more, I added some useful comments for other source files as well.

Please feel yourself free for modifying these.

I want to thank **Iztok, Jr**. for guiding me through this development.

### CODE REVIEW

**Comment by sisco0** [comment]
Please, review tests performed, as reproduction errors are thrown because of random number generator.
This happens not only at this algorithm, but for others as well.

**Comment by sisco0** [comment]
Accepted at my fork the changes proposed by @firefly-cpp .

**Comment by sisco0** [comment]
Reproduction tests errors were fixed successfully.

**Comment by sisco0** [comment]
I added some fixes for flake8 styling over hho.py file so it goes well with it.

**Review by GregaVrbancic — APPROVED** [review]

**Pull request merged**
