### PR TITLE
Add pytest-testmon to reduce the execution time of tests.

### PR DESCRIPTION
**Pull request by GregaVrbancic**
### Summary

Attempt to utilize pytest-testmon to reduce the execution time of tests when PR is created or updated. After a successful test run with the testmon enabled, the next job is running all tests.

### CODE REVIEW

**Comment by firefly-cpp** [comment]
Excellent idea @GregaVrbancic!

**Comment by sisco0** [comment]
This is a great idea for sure. Selective tests are a good thing for our suite.

**Comment by GregaVrbancic** [comment]
@ghworkflow please help me

**Comment by GregaVrbancic** [comment]
@ghworkflow list workflows

**Pull request merged**
