### PR TITLE
New algorithm: iL-SHADE

### PR DESCRIPTION
**Pull request by GregaRubin**
### Summary

I am proposing an implementation of the iL-SHADE algorithm. The algorithm was proposed in the paper "iL-SHADE: Improved L-SHADE Algorithm for Single Objective Real-Parameter Optimization" by Janez Brest, Mirjam Sepesy Maućec, Borko Bošković. 

### Other Information

I created another file in the modified algorithms and my algorithm class inherited from the SHADE algorithm. I also added my algorithm to the __init__ file.

### CODE REVIEW

**Comment by firefly-cpp** [comment]
Thanks for your contribution. Please also add tests and run examples before the review of this code contribution.

**Comment by firefly-cpp** [comment]
@zStupan

**Review by zStupan — CHANGES_REQUESTED** [review]
The algorithm looks good. Please add tests and examples

**Comment by firefly-cpp** [comment]
LGTM! @zStupan, what do you think?

**Review by zStupan — APPROVED** [review]

**Review by firefly-cpp — APPROVED** [review]

**Pull request merged**
