### PR TITLE
Benchmark refactor

### PR DESCRIPTION
**Pull request by zStupan**
### Summary
- Renamed class `Benchmark` to `Problem` and niapy/benchmarks to niapy/problems. I feel like that makes more sense and is more general. Benchmark sounds like it's only for testing and might confuse a new user trying to implement their own optimization problem.
- Made `Problem` an abstract class.
- All problems now have a `dimension` attribute, and the lower and upper bounds are numpy arrays of size `dimension`, as opposed to floats. Because of this I also had to rewrite the local and global seeding methods of the Forrest Optimization Algorithm and change a dtype parameter to float in Firefly Algorithm which should've been done anyway.
- The Task class constructor has been rewritten so that if the `problem` argument is a string, a new problem will be constructed from the `dimension`, `lower` and `upper` arguments, if they're provided (not None), otherwise the Problem's defaults will be used. If `problem` is an instance of the problem class, then that problem will be used and the dimension and bounds arguments will be ignored. The dimension, lower and upper attributes of the task are then set to those of  self.problem.
- Task.eval now calls Problem.evaluate(x).
- Problem.evaluate checks if the dimension of the input solution `x` matches the problem dimension and raises a ValueError if it doesn't. If the dimensions match it returns the function value of `x`, which is calculated by the _evaluate method. I was thinking for the future, that this method could also take a whole population and evaluate it either sequentially or in parallel, in batches, but for now it only does the dimension check.
- Problem._evaluate is an abstract method which should contain the actual objective function implementation.
- All Problem implementations were rewritten to make use of numpy instead of for loops, which should make them faster. It's only a little less than a minute improvement on test performance on my machine. The only ones I didn't know how to write in numpy form were Katsuura and Weierstrass.
- I've removed all the static `Name` variables from problems. Instead I've implemented a name method in the problem base class which just returns the instances class name. I'm planning to do this for the Algorithm class as well in a future pull request.
-  Updated the docs and examples to include these changes.
- Fixed some docstrings.
- Made the full_array method and its tests faster and easier to read.
- Removed the plot methods from the Problem class. I'm intending to add a plot.py module to util in the future.

### CODE REVIEW

**Comment by firefly-cpp** [comment]
@zStupan, Thanks. Your PR looks brilliant!

I have just one additional request for you. It seems that many users of NiaPy have
a problems with understanding our Benchmark (now Problem) component. In line with this,
it prevents them from using NiaPy in solving their own problems. Thus, I would like
to recommend you to provide a short as well as detailed tutorial about using the "Problem"
component. Is there any possibility to create a step by step tutorial, where you show the
use of "Problem" component on one selected real-world optimization problem?

This tutorial may be placed in one .md file (similarly to Algorithms.md; Contributing.md).

What do you think?

**Comment by zStupan** [comment]
I'll try. That would solve #215. It's probably best to put it in the docs as a subsection, similar to the pyswarms docs linked in the issue.

**Comment by firefly-cpp** [comment]
Excellent @zStupan. Maybe simple hyperparameter tuning? Something like this?: https://grega.xyz/2018/05/how-to-utilize-niapy-for-solving-knn-parameter-optimization-problem/

@GregaVrbancic, any comments?

**Comment by GregaVrbancic** [comment]
It looks great to me. Regarding the example, hyper-parameter optimization or feature selection is quite a popular problem lately.

**Comment by zStupan** [comment]
I messed up the branch :sweat_smile: I'll close this PR and open a new one. 

@GregaVrbancic I can do both hyperparameter tuning and feature selection.

**Comment by GregaVrbancic** [comment]
@zStupan no problem 😄 awesome if you can do both! 🚀

**Pull request closed without merging**
