### PR TITLE
add hybrid bat algorithm implementation with example

### PR DESCRIPTION
**Pull request by GregaVrbancic**
- add hba implementation
- add usage example
- add hba to list of featured algorithms in README.md

In .pylint.ini I disabled similarity checking, because of the hba and bat implementation similarity.

### CODE REVIEW

**Comment by GregaVrbancic** [comment]
@firefly-cpp please review HBA implementation. If everything looks good add **LGTM** label to pull request. 

Regarding HBA, should we consider making the *F* and *CR* parameters adjustable via class constructor?

**Comment by firefly-cpp** [comment]
Thanks for PR. It seems correct. However, we should consider making the F and CR parameters adjustable via class constructor.

**Comment by GregaVrbancic** [comment]
We could make F and CR optional constructor parameters with default values 0.5 for F and 0.9 for CR.

**Comment by firefly-cpp** [comment]
OK.

**Pull request merged**
