### PR TITLE
doc: CONTRIBUTE NEW ALGORITHM

### PR DESCRIPTION
**Pull request by firefly-cpp**
This draft document summarizes the main instructions for contributing/adding a new algorithm to the niapy framework.

### CODE REVIEW

**Comment by firefly-cpp** [comment]
The document is now in the creation stage. For now, I am moving to Code structure. Anyway, reviewing this document during the development is more than welcome.

**Comment by firefly-cpp** [comment]
@zstupan, please add sample code snippets in the current steps

**Comment by zStupan** [comment]
@firefly-cpp I hope this is ok. I just added added snippets from the Bat Algorithm implementation.

**Comment by firefly-cpp** [comment]
Thanks, @zStupan. @GregaVrbancic, what do you think?

**Comment by GregaVrbancic** [comment]
Great, it looks good to me

**Pull request merged**
