### PR TITLE
WIP: Add callbacks

### PR DESCRIPTION
**Pull request by zStupan**
### Summary

- Added callback functionality (closes issue #401).
- Removed `run_task` and `iteration_generator` methods from the Algorithm class. All the functionality has now been moved directly to `Algorithm.run`.
- Replaced the deprecated numpy function `np.product` with `np.prod`
- Added before_run and after_run callbacks (could maybe be used for some setup / cleanup)
- Added a reference to the algorithm object in the Callback class.

### Additional Information

Callbacks can be implemented by extending the `Callback` base class. They can be passed to an algorithm in a list like so:
```python
from niapy.callbacks import Callback
from niapy.algorithms.basic import BatAlgorithm
from niapy.task import Task


class PrintMeanFitness(Callback):
    def __init__(self):
        super().__init__()

    def after_iteration(self, population, fitness, best_x, best_fitness, **params):
        print(fitness.mean())


ba = BatAlgorithm(callbacks=[PrintMeanFitness()])
griewank = Task('griewank', max_evals=1000)

ba.run(griewank)
```

### CODE REVIEW

**Comment by firefly-cpp** [comment]
Thanks, @zStupan! Please also add one straightforward example showing this feature.

**Comment by firefly-cpp** [comment]
Unfortunately, CI workflow is failing (probably problems with dependencies).

**Comment by zStupan** [comment]
@firefly-cpp There seems to be a problem with the "pytest-custom-exit-code" plugin installed from [this repo](https://github.com/GregaVrbancic/pytest-custom_exit_code.git) by @GregaVrbancic. It adds an @ after the url for some reason.

Can I remove the dependency? I'm not sure what it does exactly

**Comment by GregaVrbancic** [comment]
As far as I can remember this should be some legacy dependency and probably not needed anymore.

**Comment by zStupan** [comment]
Now there's an issue with installing MacFSEvents. I have no idea how to fix this

**Comment by firefly-cpp** [comment]
Let's switch to poetry as soon as possible. What do you think? We can omit several legacy dependencies and rely on pytest.

**Comment by zStupan** [comment]
I agree, I'll get to work on that in a separate PR

**Comment by firefly-cpp** [comment]
OK. Anyway, I will merge this PR.

**Comment by firefly-cpp** [comment]
Thanks, @zStupan.

**Pull request merged**
