### PR TITLE
Attempt to fix scrutinizer

### PR DESCRIPTION
**Pull request by GregaVrbancic**
### Summary

For some time now, the scrutinizer is failing to conduct code analysis since it fails running "python setup.py install". 

More info about error: https://scrutinizer-ci.com/g/NiaOrg/NiaPy/inspections/f1bbc729-032b-453a-bb7f-1b855fad1531

In this PR the python version is updated to 3.9.5

Any additional suggestions are more than welcome.

### CODE REVIEW

**Comment by GregaVrbancic** [comment]
@zStupan maybe you have some idea, why other tests are failing since there are no other changes than in scrutinizer.yml file?

**Comment by zStupan** [comment]
There was a  linter errors in #316. Specifically in setup.py `MINIMUM_PYTHON_VERSION = (3,6)` should be `MINIMUM_PYTHON_VERSION = (3, 6)`, with a space after the comma. I fixed this in my PR.

**Comment by GregaVrbancic** [comment]
Oh, I see. Thanks for the quick reply 😃

**Comment by GregaVrbancic** [comment]
Closing this PR, since the fixes were applied in #321

**Pull request closed without merging**
