### PR TITLE
WIP: Switch to poetry

### LINKED ISSUE #400: Program versions
**Steps to reproduce**
`make doctor`

**Actual behavior**
```
bin/verchew

Checking for Make...

$ make --version
GNU Make 4.3
~ MATCHED: GNU Make

Checking for Python...

$ python --version
Python 3.11.0
? EXPECTED: Python 3.6.

Checking for pipenv...

$ pipenv --version
pipenv, version 2023.4.29
x EXPECTED: 9.

Checking for pandoc...

$ pandoc --version
pandoc 2.17.1.1
~ MATCHED: 1.

Checking for Graphviz...

$ dot -V
dot - graphviz version 2.43.0 (0)
~ MATCHED: 2.

Results: ~ ? x ~ ~
```

**Problem**
Program version do not mach expected ones. Pipenv has different version names for different installs. I build Python from source and from this build I update pip and with pip I install Pipenv.

**System configuration**

 - OS: Linux, Ubuntu 23.04
 - Python version: 3.11.0

### LINKED ISSUE #403: Switch to Poetry

### PR DESCRIPTION
**Pull request by zStupan**
### Summary
- Switched from Pipenv to poetry for dependency management.
- Removed unnecessary config files.
- Updated the main workflow.
- Updated docs
- The minimum required python version is now 3.9.
- Moved tests out of the niapy package.
- Closes #403
- Closes #400 

### TODO:
- I haven't figured out the publishing to pypi and conda workflows/config yet
- Use [ruff](https://docs.astral.sh/ruff/) for linting and fixing code style errors. The config can be written directly to pyproject.toml.

### CODE REVIEW

**Comment by firefly-cpp** [comment]
Thanks, @zStupan

**Comment by firefly-cpp** [comment]
LGTM

**Comment by firefly-cpp** [comment]
@GregaVrbancic, can you try to build it and publish a new release on Pypi?

**Comment by zStupan** [comment]
I'm not sure about conda, but this is a workflow that should work for PyPI:

```yaml
name: Build and Publish NiaPy Pypi Package

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build project for distribution
        run: poetry build

      - name: Check Version
        id: check-version
        run: |
          [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || echo prerelease=true >> $GITHUB_OUTPUT

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
```

**Pull request merged**
