### PR TITLE
Development

### PR DESCRIPTION
**Pull request by kb2623**
# New algorithms
* Center Particle Swarm Optimization
* Comprehensive Learning Particle Swarm Optimizer
* Opposition Velocity Clamping Particle Swarm Optimization
* Mutated Center Particle Swarm Optimization
* Mutated Center Unified Particle Swarm Optimization
* Mutated Particle Swarm Optimization

# Enhancements
* Now should be possible for all algorithms to set the initialization method.

# Changes
* New interface for algorithms (many algorithms needed a rework)
* New test case for algorithms
* Algorithms got changes based on issue #188 

# Solved issues:
* #218 
* #185 if it was not before
* #187 
* #186 
* #188 
* #220

### CODE REVIEW

**Comment by GregaVrbancic** [comment]
I have fixed the integration problems, cleaned up unnecessary comments, and fixed backward compatibility problems for Python 2.7.x.

**Comment by GregaVrbancic** [comment]
@kb2623, we have to solve just one last failure for Python2. Do you have any idea what should we do about this: https://github.com/NiaOrg/NiaPy/commit/a874bfea24da56b6e9b1a7a3889b6903a6b3df87/checks?check_suite_id=305072883#step:9:884

**Comment by kb2623** [comment]
Fix for #220  

Fixed method for getting data for convergence plot. Use method `plot` or use `return_conv`.

**Comment by GregaVrbancic** [comment]
All of the tests are passing :tada: Do we agree to merge this pull request @kb2623 @firefly-cpp?

**Pull request merged**
