### PR TITLE
L-SHADE implementation

### PR DESCRIPTION
**Pull request by AlesGartner**
### Summary

Added Implementation Success-history based adaptive differential evolution algorithm with Linear population size reduction in shade.py. Also added test (test_shade.py) and example (run_shade) files and updated algorithms/modified/__innit__.py .

The algorithm is explained this <a href="https://ieeexplore.ieee.org/abstract/document/6900380">article</a>.

I created a Individual class SolutionSHADE  for the algorithm. SolutionSHADE additionally stores f and cr values of each Individual.

The SuccessHistoryAdaptiveDifferentialEvolution class implements the SHADE 1.1 algorithm which is the base for the L-SHADE algorithm implemented in the LpsrSuccessHistoryAdaptiveDifferentialEvolution class.

The algorithm uses the current-to-pbest mutation strategy with binomial crossover which is implemented in the cross_curr2pbest1 function. Trial vectors created by this function are repaired with the parent_medium function.

### CODE REVIEW

**Comment by firefly-cpp** [comment]
Thank you, @AlesGartner for all the hard work! I want to ask @zStupan for an initial review of this implementation.

**Review by zStupan — APPROVED** [review]
Looks good! We can merge if the tests pass and the algorithms produce similar results to the ones in the paper.

**Review by zStupan — DISMISSED** [review]

**Comment by firefly-cpp** [comment]
@GregaVrbancic, can you please check the following issue regarding the flake settings?

**from flake8.options.config import ConfigFileFinder
ImportError: cannot import name 'ConfigFileFinder' from 'flake8.options.config' (/home/runner/work/NiaPy/NiaPy/.venv/lib/python3.8/site-packages/flake8/options/config.py)** 

@AlesGartner, are the results achieved by your implementation similar to those provided by the original implementation? Can you please also compare your results with the original publication?

**Comment by AlesGartner** [comment]
> @GregaVrbancic, can you please check the following issue regarding the flake settings?
> 
> **from flake8.options.config import ConfigFileFinder ImportError: cannot import name 'ConfigFileFinder' from 'flake8.options.config' (/home/runner/work/NiaPy/NiaPy/.venv/lib/python3.8/site-packages/flake8/options/config.py)**
> 
> @AlesGartner, are the results achieved by your implementation similar to those provided by the original implementation? Can you please also compare your results with the original publication?

I did some tests on cec2014 functions using the <a href="https://github.com/NiaOrg/NiaPy-examples">NiaPy-examples</a> repo.

I ran my L-SHADE implementation with default parameters (which i assume run_cec.py uses)of population_size= 180, extern_arc_rate= 2.6, pbest_factor=0.11 and hist_mem_size=6  which i believe where used in <a href="https://ieeexplore.ieee.org/abstract/document/6900380">the publication</a>

i did 51 runs on test functions 2, 5, 14, 19 and 27 of dimensionality D=10 and got the following results:
(numbers shown are based of the error value between the best fitness values found in each run and the
true optimal value)

<table>
<tr>
<th>F. num.</th>
<th>Best</th>
<th>Worst</th>
<th>Median</th>
<th>Mean</th>
<th>Std.</th>
</tr>
<tr>
<td>2</td>
<td>0.00e+00</td>
<td>0.00e+00</td>
<td>0.00e+00</td>
<td>0.00e+00</td>
<td>0.00e+00</td>
</tr>
<tr>
<td>5</td>
<td>2.34e-01</td>
<td>2.0e+01</td>
<td>2.0e+01</td>
<td>1.35e+01</td>
<td>8.83e+00</td>
</tr>
<tr>
<td>14</td>
<td>1.48e-02</td>
<td>1.48e-01</td>
<td>5.05e-02</td>
<td>5.39e-02</td>
<td>2.02e-02</td>
</tr>
<tr>
<td>19</td>
<td>5.30e-02</td>
<td>1.04e+00</td>
<td>2.13e-01</td>
<td>2.30e-01</td>
<td>1.39e-01</td>
</tr>
<tr>
<td>27</td>
<td>1.06e+00</td>
<td>4.00e+02</td>
<td>1.73e+00</td>
<td>1.01e+02</td>
<td>1.49e+02</td>
</tr>
</table>

Results in the publication:

<table>
<tr>
<th>F. num.</th>
<th>Best</th>
<th>Worst</th>
<th>Median</th>
<th>Mean</th>
<th>Std.</th>
</tr>
<tr>
<td>2</td>
<td>0.0e+00</td>
<td>0.0e+00</td>
<td>0.0e+00</td>
<td>0.0e+00</td>
<td>0.0e+00</td>
</tr>
<tr>
<td>5</td>
<td>1.5e-01</td>
<td>2.0e+01</td>
<td>2.0e+01</td>
<td>1.4e+01</td>
<td>8.8e+00</td>
</tr>
<tr>
<td>14</td>
<td>4.5e-02</td>
<td>1.6e-01</td>
<td>7.6e-02</td>
<td>8.1e-02</td>
<td>2.6e-02</td>
</tr>
<tr>
<td>19</td>
<td>1.3e-02</td>
<td>3.8e-01</td>
<td>6.2e-02</td>
<td>7.7e-02</td>
<td>6.4e-02</td>
</tr>
<tr>
<td>27</td>
<td>8.5e-01</td>
<td>4.0e+02</td>
<td>1.5e+00</td>
<td>5.8e+01</td>
<td>1.3e+02</td>
</tr>
</table>

**Comment by firefly-cpp** [comment]
Thanks @AlesGartner! 

It looks consistent. Can you please also copy one or two results tables for the dimensions higher than 10, e.g., 20, 30, or 50?

When #391 is ready, we can merge this PR.

**Comment by AlesGartner** [comment]
I ran tests on D=30 and D=50, but these took really long to finish, so i only did 10 runs per problem function.

<h3> D=30 </h3>

these tests where ran with population_size = 540 (18 * D)

<table>
<tr>
<th>F. num.</th>
<th>Best</th>
<th>Worst</th>
<th>Median</th>
<th>Mean</th>
<th>Std.</th>
</tr>
<tr>
<td>5</td>
<td>2.01e+01</td>
<td>2.02e+01</td>
<td>2.01e+01</td>
<td>2.01e+01</td>
<td>2.29e-02</td>
</tr>
<tr>
<td>9</td>
<td>6.92e+00</td>
<td>1.12e+01</td>
<td>9.10e+00</td>
<td>9.03e+00</td>
<td>1.23e+00</td>
</tr>
<tr>
<td>14</td>
<td>1.56e-01</td>
<td>4.32e-01</td>
<td>1.95e-01</td>
<td>2.16e-01</td>
<td>7.65e-02</td>
</tr>
<tr>
<td>19</td>
<td>3.19e+00</td>
<td>4.88e+00</td>
<td>4.36e+00</td>
<td>4.21e+00</td>
<td>5.56e-01</td>
</tr>
</table>

Results in the publication(based on 51 runs):

<table>
<tr>
<th>F. num.</th>
<th>Best</th>
<th>Worst</th>
<th>Median</th>
<th>Mean</th>
<th>Std.</th>
</tr>
<tr>
<td>5</td>
<td>2.0e+01</td>
<td>2.0e+01</td>
<td>2.0e+01</td>
<td>2.0e+01</td>
<td>3.7e-02</td>
</tr>
<tr>
<td>9</td>
<td>3.3e+00</td>
<td>9.2e+00</td>
<td>7.1e+00</td>
<td>6.8e+00</td>
<td>1.5e+00</td>
</tr>
<tr>
<td>14</td>
<td>1.8e-01</td>
<td>3.0e-01</td>
<td>2.4e-01</td>
<td>2.4e-01</td>
<td>3.0e-02</td>
</tr>
<tr>
<td>19</td>
<td>1.6e+00</td>
<td>4.9e+00</td>
<td>3.9e+00</td>
<td>3.7e+00</td>
<td>6.8e-01</td>
</tr>
</table>


<h3>D=50</h3>

these tests where ran with population_size = 900 (18 * D)

<table>
<tr>
<th>F. num.</th>
<th>Best</th>
<th>Worst</th>
<th>Median</th>
<th>Mean</th>
<th>Std.</th>
</tr>
<tr>
<td>5</td>
<td>2.02e+01</td>
<td>2.03e+01</td>
<td>2.03e+01</td>
<td>2.03e+01</td>
<td>2.19e-02</td>
</tr>
<tr>
<td>9</td>
<td>1.06e+01</td>
<td>1.78e+01</td>
<td>1.37e+01</td>
<td>1.37e+01</td>
<td>2.42e+00</td>
</tr>
<tr>
<td>14</td>
<td>2.02e-01</td>
<td>6.54e-01</td>
<td>2.50e-01</td>
<td>3.02e-01</td>
<td>1.34e-01</td>
</tr>
<tr>
<td>19</td>
<td>6.73e+00</td>
<td>1.23e+01</td>
<td>7.69e+00</td>
<td>8.90e+00</td>
<td>2.17e+00</td>
</tr>
</table>

Results in the publication(based on 51 runs):

<table>
<tr>
<th>F. num.</th>
<th>Best</th>
<th>Worst</th>
<th>Median</th>
<th>Mean</th>
<th>Std.</th>
</tr>
<tr>
<td>5</td>
<td>2.0e+01</td>
<td>2.0e+01</td>
<td>2.0e+01</td>
<td>2.0e+01</td>
<td>4.6e-02</td>
</tr>
<tr>
<td>9</td>
<td>5.4e+00</td>
<td>1.5e+01</td>
<td>1.1e+01</td>
<td>1.1e+01</td>
<td>2.1e+00</td>
</tr>
<tr>
<td>14</td>
<td>2.4e-01</td>
<td>3.5e-01</td>
<td>2.9e-01</td>
<td>3.0e-01</td>
<td>2.5e-02</td>
</tr>
<tr>
<td>19</td>
<td>5.4e+00</td>
<td>1.2e+01</td>
<td>7.9e+00</td>
<td>8.3e+00</td>
<td>1.8e+00</td>
</tr>
</table>

**Pull request merged**
