### PR TITLE
Removed scipy dependency

### PR DESCRIPTION
**Pull request by zStupan**
Implemented all the changes discussed in #303, as well as:

- Removed all other python2 backwards compatibility libraries from dev dependencies
- Removed \_\_future\_\_ imports
- Fixed some typos in the readme's

### CODE REVIEW

**Comment by firefly-cpp** [comment]
Thanks @zStupan 

You can not imagine how much your help is appreciated :)

**Comment by firefly-cpp** [comment]
One remark

Have you already compared the results obtained by the new implementation against the previous one?

**Comment by firefly-cpp** [comment]
Anyway, merging PR to master.

**Comment by zStupan** [comment]
Only the results in cuckoo search are slightly different, because I used an [approximate numerical method](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.49.4677), but it's the same method used in the MATLAB code of the original author of the algorithm. Scipy uses a different method.

**Pull request merged**
