### PR TITLE
Updating development branch

### PR DESCRIPTION
**Pull request by kb2623**
Update to development version of NiaPy.
Tests will fail.

### CODE REVIEW

**Comment by kb2623** [comment]
Tests will fail

**Comment by GregaVrbancic** [comment]
This PR should also address issue #155 if it is not already.

**Comment by kb2623** [comment]
It is almost the same code as in my master branch. This branch has three additional algorithms that are not yet implemented. For some of them `pylint` fails.

**Comment by GregaVrbancic** [comment]
Look good to me.

**Pull request merged**
