### PR TITLE
Initial implementation of Clonal Selection Algorithm

### PR DESCRIPTION
**Pull request by andrazperson**

### CODE REVIEW

**Comment by firefly-cpp** [comment]
@zStupan, Please make this code consistent with the recent interface. Thanks!

**Comment by zStupan** [comment]
Will do, I don't have a lot of time right now, but I'll get to it.

**Comment by firefly-cpp** [comment]
Thanks @zStupan!

**Comment by zStupan** [comment]
Done. @andrazperson I opened a PR on your fork.

**Review by zStupan — APPROVED** [review]

**Comment by GregaVrbancic** [comment]
@all-contributors please add @andrazperson  as a code contributor.

**Pull request merged**
